name: Reconcile Benchmark Source Files

on:
  workflow_dispatch:

jobs:
  pull-benchmark-source:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Pull Benchmark Source
        run: |
          git fetch --all

          git checkout benchmark
          git pull origin benchmark
          
          git checkout master
          git pull origin master
          
          git rm -r --ignore-unmatch --cached Source/ Examples/ || true
          rm -r Source/ Examples/ || true
          
          git restore --source=benchmark --staged --worktree Source/ Examples/
          git add --renormalize Source/* Examples/*
          
          if git diff --cached --quiet; then
              echo "No changes to commit on master"
          else
              git commit -m "Reconcile Source with benchmark branch"
              git push origin master
          fi